config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :views
  devise_for :usuarios, :controllers => {:omniauth_callbacks => "callbacks"}
  resources :eventos
  resources :eventos
  resources :tipo_eventos
  resources :tipo_eventos
  resources :inscricoes
  resources :avaliacoes
  root to: "eventos#index"

end

app/models/evento.rb
class Evento < ActiveRecord::Base
	belongs_to :tipo_evento
	has_many :inscricoes
	has_many :avaliacoes
validates :nome,
		uniqueness: true,
		presence: true,
		length: {minimum: 10, 
			maximum:100}
validates :descricao,
		presence: true,
		length: {minimum: 10, 
			maximum:1000}
validates :datainicio, 
		presence: true
		 			
validates :datafim, 
		presence: true,
		date: { :after_or_equal_to => :datainicio}

validates :local,
		presence: true,
		length: {minimum: 10, 
			maximum:100}

validates :site,
		presence: true,
		  :format => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix  
 

validates :vagasdisponiveis, 
		numericality: { greater_than: 0, only_integer: true }

validates :imagem,
		presence: true,
		length: {minimum: 10, 
			maximum:100}

validates :palestrante,
		presence: true,
		length: {minimum: 10, 
			maximum:100}
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
   before_action :set_evento, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_usuario!, except: [:show, :index]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    if (!current_usuario.blank?)
      @avaliacao =  current_usuario.avaliacoes.where(evento_id:@evento.id).first
      if (@avaliacao.blank?)
        @avaliacao = Avaliacao.new
      end
    else
      @avaliacao = Avaliacao.new
    end
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento criado com sucesso.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nome, :descricao, :datainicio, :datafim, :local, :endereco, :site, :vagasdisponiveis, :palestrante, :imagem)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "erro") %> Não foi possível salvar Evento:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :datainicio %><br>
    <%= f.datetime_select :datainicio %>
  </div>
  <div class="field">
    <%= f.label :datafim %><br>
    <%= f.datetime_select :datafim %>
  </div>
  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :palestrante %><br>
    <%= f.text_field :palestrante %>
  </div>
  <div class="field">
    <%= f.label :imagem %><br>
    <%= f.text_field :imagem %>
  </div>
  <div class="field">
    <%= f.label :vagasdisponiveis %><br>
    <%= f.number_field :vagasdisponiveis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
    <% @eventos.each do |evento| %>

            <div class="artigo" role="article">
              <div class="row">
                <div class="col-md-4">
                  <a href="#" title="">
                    <%= image_tag evento.imagem %>
                  </a>
                </div>
                <div class="col-md-8">
                  <h2><a href="#"><%= evento.nome %></a></h2>
                  <p><%= evento.descricao %></p>
                  <p><%= evento.datainicio %></p>
                  <p><%= evento.endereco %></p>
                  <p>Vagas disponíveis: <%= evento.vagasdisponiveis  -  evento.inscricoes.count() %></p>
                  <!--
                  <p>
                    <%= link_to 'Editar', edit_evento_path(evento) %> |
                    <%= link_to 'Apagar', evento, method: :delete, data: { confirm: 'Tem certeza?' } %>
                  </p>
                  //-->

                  <%= link_to 'Saiba Mais', evento %>
                </div>
              </div><!-- div row conteudo -->
            </div>
    <% end %>
            
    <br>

   <!-- <%= link_to 'Novo Evento', new_evento_path %> //-->

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<div class="row">
  <div class="col-md-8">
    <%= image_tag( @evento.imagem, width: '50px') %>
  </div>                
</div>
<div class="row">
  <div class="col-md-8">
<p>
  <strong>Nome:</strong>
  <%= @evento.nome %>
</p>
<p>
  <strong>Descricao:</strong>
  <%= @evento.descricao %>
</p>

<p>
  <strong>Datainicio:</strong>
  <%= @evento.datainicio %>
</p>

<p>
  <strong>Datafim:</strong>
  <%= @evento.datafim %>
</p>

<p>
  <strong>Local:</strong>
  <%= @evento.local %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @evento.endereco %>
</p>

<p>
  <strong>Site:</strong>
  <%= link_to @evento.site , @evento.site  %> 
</p>

<p>
  <strong>Vagasdisponiveis:</strong>
  <%= @evento.vagasdisponiveis  -  @evento.inscricoes.count() %>
</p>


<!--TEM INSCRICAO EXIBE BOTAO PARA SAIR //-->

<% if usuario_signed_in? && (current_usuario.inscricoes.where(evento_id:@evento.id).count) > 0 %>
<a  class="btn btn-danger" data-confirm="Tem certeza?" rel="nofollow" data-method="delete" href="/inscricoes/<%=current_usuario.inscricoes.where(evento_id:@evento.id).first.id%>">Cancelar Inscrição</a>

<!--SEM VAGAS//-->
<% elsif (@evento.vagasdisponiveis  -  @evento.inscricoes.count())>0 and (@evento.datafim > Date.current()) %> 
<form action='/inscricoes' method="post">
   <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
   <input type='hidden' name='inscricao[evento_id]' value="<%= @evento.id %>"/>
  <button type="submit" class="btn btn-success">Quero Participar</button>
</form>
<!--AVALIAR EVENTO//-->
<% end %>
<% if (@evento.datainicio < Date.current()) %> 
<%= form_for(@avaliacao) do |f| %>
  
   <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
   <input type='hidden' name='avaliacao[evento_id]' value="<%= @evento.id %>"/>
    <br>
    <p>
      <strong>Avalie o evento:</strong>
    </p>

                      <%= radio_button("avaliacao", "nota", "1")%>Ruim 
                       <%= radio_button("avaliacao", "nota", "2")%>Médio 
                       <%= radio_button("avaliacao", "nota", "3")%>Bom 
                       <%= radio_button("avaliacao", "nota", "4")%>Ótimo
                       <%= radio_button("avaliacao", "nota", "5")%>Excelente

   <br> <br> 
   <textarea class="form-control" rows="4" name="avaliacao[texto]"><%= @avaliacao.texto%></textarea>
   <br>
  <button type="submit" class="btn btn-success">Enviar avaliação</button>
<% end %>
<% end %>


  </div>                
</div>

<div class="row">
  <div class="col-md-8">
    <p><br>    
      <img src="http://maps.google.com/maps/api/staticmap?size=1200x1200&maptype=roadmap&sensor=false&markers=color:red|label:A|<%= @evento.endereco %>" width="100" alt="<%= @evento.nome %>"></img>
    </p>
  </div>                
</div>