config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :views
  devise_for :usuarios, :controllers => {:omniauth_callbacks => "callbacks"}
  resources :eventos
  resources :eventos
  resources :tipo_eventos
  resources :tipo_eventos
  resources :inscricoes
  resources :avaliacoes
  root to: "eventos#index"

end

app/models/tipo_evento.rb
class TipoEvento < ActiveRecord::Base
	has_many :evento
validates :Nome,
		uniqueness: true,
		presence: true,
		length: {minimum: 5, 
			maximum:100}
end

app/controllers/tipo_eventos_controller.rb
class TipoEventosController < ApplicationController
  before_action :set_tipo_evento, only: [:show, :edit, :update, :destroy]

  # GET /tipo_eventos
  # GET /tipo_eventos.json
  def index
    @tipo_eventos = TipoEvento.all
  end

  # GET /tipo_eventos/1
  # GET /tipo_eventos/1.json
  def show
  end

  # GET /tipo_eventos/new
  def new
    @tipo_evento = TipoEvento.new
  end

  # GET /tipo_eventos/1/edit
  def edit
  end

  # POST /tipo_eventos
  # POST /tipo_eventos.json
  def create
    @tipo_evento = TipoEvento.new(tipo_evento_params)

    respond_to do |format|
      if @tipo_evento.save
        format.html { redirect_to @tipo_evento, notice: 'Tipo evento criado com sucesso.' }
        format.json { render :show, status: :created, location: @tipo_evento }
      else
        format.html { render :new }
        format.json { render json: @tipo_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_eventos/1
  # PATCH/PUT /tipo_eventos/1.json
  def update
    respond_to do |format|
      if @tipo_evento.update(tipo_evento_params)
        format.html { redirect_to @tipo_evento, notice: 'Tipo evento alterado com sucesso..' }
        format.json { render :show, status: :ok, location: @tipo_evento }
      else
        format.html { render :edit }
        format.json { render json: @tipo_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_eventos/1
  # DELETE /tipo_eventos/1.json
  def destroy
    @tipo_evento.destroy
    respond_to do |format|
      format.html { redirect_to tipo_eventos_url, notice: 'Tipo evento excluído com sucesso..' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_evento
      @tipo_evento = TipoEvento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_evento_params
      params.require(:tipo_evento).permit(:Nome)
    end
end

app/helpers/tipo_eventos_helper.rb
module TipoEventosHelper
end

app/views/tipo_eventos/_form.html.erb
<%= form_for(@tipo_evento) do |f| %>
  <% if @tipo_evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_evento.errors.count, "erro") %> Não foi possível salvar Tipo de Evento:</h2>

      <ul>
      <% @tipo_evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nome %><br>
    <%= f.text_field :Nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_eventos/edit.html.erb
<h1>Editing Tipo Evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_evento %> |
<%= link_to 'Back', tipo_eventos_path %>

app/views/tipo_eventos/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Listing Tipo Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_eventos.each do |tipo_evento| %>
      <tr>
        <td><%= tipo_evento.Nome %></td>
        <td><%= link_to 'Show', tipo_evento %></td>
        <td><%= link_to 'Edit', edit_tipo_evento_path(tipo_evento) %></td>
        <td><%= link_to 'Destroy', tipo_evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo evento', new_tipo_evento_path %>

app/views/tipo_eventos/new.html.erb
<h1>New Tipo Evento</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_eventos_path %>

app/views/tipo_eventos/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Nome:</strong>
  <%= @tipo_evento.Nome %>
</p>

<%= link_to 'Edit', edit_tipo_evento_path(@tipo_evento) %> |
<%= link_to 'Back', tipo_eventos_path %>